{
 "title": "Dell Compellent",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>BAIE DE STOCKAGE SCv2020</span>\n</div>"
  },
  {
   "title": "Cache Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "san_cache",
     "select": [
      [
       { "params": [ "scCacheBatStat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Status Global",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "san_infos",
     "select": [
      [
       { "params": [ "san_status" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Equilibrage des ports",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "san_infos",
     "select": [
      [
       { "params": [ "san_portsBalance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "san_cache",
     "select": [
      [
       { "params": [ "scCacheBatStat" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "san_space",
     "query": "SELECT ((100 * mean(\"used_space\")) / mean(\"total_space\")) FROM \"san_space\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "total_space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 15, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "san_infos",
     "select": [
      [
       { "params": [ "san_ip" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 17, "y": 3 },
   "format": "timeticks",
   "valueName": "current",
   "targets": [
    {
     "measurement": "snmp",
     "query": "SELECT \"uptime\" FROM \"snmp\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 19, "y": 3 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "measurement": "san_infos",
     "select": [
      [
       { "params": [ "service_tag" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disks status",
   "type": "table",
   "gridPos": { "h": 27, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "scDiskNamePosition" ], "type": "tag" }
     ],
     "measurement": "san_disks",
     "query": "SELECT last(\"scCtlrTempStatus\") AS \"TempStatus\", last(\"scCtlrTempCurrentC\") AS \"Temp\" FROM \"san_temp\" WHERE $timeFilter GROUP BY \"$tag_scDiskNamePosition\"",
     "select": [
      [
       { "params": [ "scDiskHealthy" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Health" ], "type": "alias" }
      ],
      [
       { "params": [ "scDiskStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Status" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SAN Alerts",
   "type": "table",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "san_alerts",
     "query": "SELECT  last(\"scAlertStatus\") AS Status, last(\"scAlertCategory\") AS Categorie, last(\"scAlertCreateTime\") AS Date, last(\"scAlertMessage\") AS Message FROM \"san_alerts\" WHERE  (\"scAlertActive\" = 2)  AND  $timeFilter GROUP BY \"scAlertNbr\"",
     "select": [
      [
       { "params": [ "scAlertStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SRV-GRAFANA" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 15, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "scCtlrTempName" ], "type": "tag" }
     ],
     "measurement": "san_temp",
     "query": "SELECT last(\"scCtlrTempCurrentC\") FROM \"san_temp\" WHERE (\"hostname\" = 'FAR-CPL') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "scCtlrTempStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "TempStatus" ], "type": "alias" }
      ],
      [
       { "params": [ "scCtlrTempCurrentC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temp" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "san_space",
     "select": [
      [
       { "params": [ "used_space" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}